Melhoria

diff --git a/pma_create_day b/pma_create_day
--- a/pma_create_day
+++ b/pma_create_day
@@ -3,37 +3,40 @@
 function usage() {
   cat <<END
    -h                 : This help
-   -d <date>          : Date to create (yyyy-MM-dd)
-   -s <start time>    : Start time (HH:mm)
-   -e <end time>      : End time (HH:mm)
-   -i <interval time> : Interval time (HH:mm)
+   -d <date>          : Date to create (yyyy-MM-dd). Default value is today (date +'%F')
+   -s <start time>    : Start time (HH:mm). Default value is '09:00'
+   -e <end time>      : End time (HH:mm). Default value is '18:00'
+   -i <interval time> : Interval time (HH:mm). Default value is '01:00'
 END
 }
 
-if [ $# -eq 0 ]; then
-  usage
-  exit 1
-fi
-
-while getopts "h?dsei:" opt; do
+while getopts "h?d:s:e:i:" opt; do
     case "$opt" in
     h|\?)
         usage
         exit 0
         ;;
-    d)  date=$OPTARG 
-        ;;
-    s)  starttime=$OPTARG
-        ;;
-    e)  endtime=$OPTARG
-        ;;
-    i)  interval=$OPTARG
-        ;;
+    d)  date="$OPTARG" ;;
+    s)  starttime="$OPTARG" ;;
+    e)  endtime="$OPTARG" ;;
+    i)  interval="$OPTARG" ;;
 
     esac
 done
+date=${date-$(date +'%F')}
+starttime=${starttime-'09:00'}
+endtime=${endtime-'18:00'}
+interval=${interval-'01:00'}
 
-today=$(date +'%F')
 
-curl -s -X post https://pma.dextra.com.br/pma/services/criar_apontamento_diario -d token=$(cat $HOME/.pma_token)\&data=$date\&inicio=$starttime\&intervalo=$interval\&fim=$endtime
+resp=$(curl -s -X post https://pma.dextra.com.br/pma/services/criar_apontamento_diario -d token=$(cat $HOME/.pma_token)\&data=$date\&inicio=$starttime\&intervalo=$interval\&fim=$endtime)
 
+source pma_util
+handlePmaResponse "$resp"
+
+if [ $response_code != '0' ]; then
+   echo "$response_error"
+   exit 1
+fi
+
+echo "$response_msgs"
