Login/Logout

diff --git a/pma_logout b/pma_logout
--- a/pma_logout
+++ b/pma_logout
@@ -1,4 +1,23 @@
 #!/bin/bash 
 
-echo 'Logouting'
-curl -s https://pma.dextra.com.br/pma/services/invalidar_tokens
+if [ $# -lt 1 ]; then 
+  echo "Usage: $(basename $0) <username>"
+  exit 1
+fi
+
+username=$1
+
+source pma_util
+
+readPass "$username"
+
+resp=$(curl -s -X post https://pma.dextra.com.br/pma/services/invalidar_tokens -d username=$username\&password=$password)
+
+handlePmaResponse "$resp"
+
+if [ $response_code != '0' ]; then
+   echo "$response_error"
+   exit 1
+fi
+
+echo "$response_msgs"
diff --git a/pma_token b/pma_token
--- a/pma_token
+++ b/pma_token
@@ -5,11 +5,20 @@ if [ $# -lt 1 ]; then
   exit 1
 fi
 
-
 username=$1
 
-echo 'Getting Token'
-stty -echo
-read -p "Senha: " pass
-stty echo
-curl -s -X post https://pma.dextra.com.br/pma/services/obter_token -d username=$username\&password=$pass | xpath -q -e "//token/text()" > $HOME/.pma_token
+source pma_util
+
+readPass "$username"
+
+resp=$(curl -s -X post https://pma.dextra.com.br/pma/services/obter_token -d username=$username\&password=$password)
+
+handlePmaResponse "$resp"
+
+if [ $response_code != '0' ]; then
+   echo "$response_error"
+   exit 1
+fi
+
+echo $resp | xpath -q -e '//token/text()' > $HOME/.pma_token
+cat $HOME/.pma_token
